# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false

mod_id = factory_io
mod_version = 0.0.3

mc_version=1.20.1
mc_version_short=1.20
forge_version=47.3.6
parchment_version=2023.09.03-1.20.1

geckolib_version=4.4.9
jei_version=15.20.0.106

junit_version=5.10.2
